services:
  # minecraft:
  #   container_name: minecraft
  #   image: itzg/minecraft-server:latest
  #   tty: true
  #   stdin_open: true
  #   restart: unless-stopped
  #   ports:
  #     - "25565:25565"
  #   environment:
  #     EULA: "TRUE"
  #     OPS: "MightyMime"
  #     TYPE: "FABRIC"
  #     MEMORY: "6144M"
  #     MAX_PLAYERS: "10"
  #     MOTD: "Kiwi Server"
  #     ONLINE_MODE: "false"
  #     USE_MEOWICE_FLAGS: "true"
  #     DIFFICULTY: "3"
  #     VIEW_DISTANCE: "20"
  #     LEVEL: "Iglo"
  #     VANILLATWEAKS_SHARECODE: "5BAnxq"
  #     PAUSE_WHEN_EMPTY_SECONDS: "30"
  #     ENABLE_ROLLING_LOGS: "true"
  #     MODRINTH_PROJECTS: |
  #       fabric-api
  #       fabric-language-kotlin
  #       silk
  #       lithium
  #       sodium
  #       carpet
  #       ferrite-core
  #       krypton
  #       clumps
  #       veinminer
  #       lambdynamiclights
  #       collective
  #       stack-refill
  #       infinite-trading
  #       tree-harvester
  #     TZ: ${TZ}
  #   volumes:
  #     - ${DATADIR}/minecraft/data:/data

  romm:
    image: rommapp/romm:latest
    container_name: romm
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      DB_HOST: romm-db
      DB_NAME: ${ROMM_DB_NAME}
      DB_USER: ${ROMM_DB_USER}
      DB_PASSWD: ${ROMM_DB_PASS}
      ROMM_AUTH_SECRET_KEY: ${ROMM_AUTH_SECRET_KEY}
      SCREENSCRAPER_USER: ${ROMM_SCREENSCRAPER_USER}
      SCREENSCRAPER_PASSWORD: ${ROMM_SCREENSCRAPER_PASSWORD}
      RETROACHIEVEMENTS_API_KEY: ${ROMM_RETROACHIEVEMENTS_API_KEY}
      STEAMGRIDDB_API_KEY: ${ROMM_STEAMGRIDDB_API_KEY}
      HASHEOUS_API_ENABLED: true
      # LAUNCHBOX_API_ENABLED: true
    volumes:
      - ${DATADIR}/romm/resources:/romm/resources
      - ${DATADIR}/romm/config:/romm/config
      - ${DATADIR}/romm/assets:/romm/assets
      - ${DATADIR}/romm/redis:/romm/redis
      - ${GAMEDIR}:/romm/library
    ports:
      - 8055:8080
    depends_on:
      romm-db:
        condition: service_healthy
        restart: true
    networks:
      - caddy
      - default
    labels:
      # Caddy
      caddy: games.${WEBSITE}
      caddy.reverse_proxy: "{{upstreams 8080}}"
      # Plato
      plato.category: "Media"

  romm-db:
    image: mariadb:latest
    container_name: romm-db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${ROMM_DB_PASS}
      MARIADB_DATABASE: ${ROMM_DB_NAME}
      MARIADB_USER: ${ROMM_DB_USER}
      MARIADB_PASSWORD: ${ROMM_DB_PASS}
    volumes:
      - ${DATADIR}/romm/db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 30s
      start_interval: 10s
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default

networks:
  default:
  caddy:
    external: true
