#!/bin/bash
# 2D single-server Kuerbenetes-ish docker-compose manager with machine
set -euo pipefail



GREEN='\033[0;32m'
RED='\033[0;31m'
RESET='\033[0m'

# Check Caddy Docker Network
NETWORK_NAME="caddy"
if ! docker network ls --format '{{.Name}}' | grep -wq "$NETWORK_NAME"; then
    echo -e "${GREEN}Creating docker network '$NETWORK_NAME'${RESET}"
    docker network create "$NETWORK_NAME"
fi

# Choose Project List
case "$(hostname)" in
    "kiwi")
        projects=(
            "admin"
            "arrsuite"
            "games"
            "homeassistant"
            "immich"
            "media"
            "misc"
            "nextcloud"
        )
        ;;
    "lion")
        projects=(
            "unifi"
        )
        ;;
    *)
        echo -e "${RED}Unknown machine${RESET}"
        exit 1
        ;;
esac

if [[ $# -lt 1 ]]; then
    echo -e "${RED}Error: Missing arguments${RESET}"
    exit 1
fi

# Start Docker Projects
for project in "${projects[@]}"; do
    echo -e "${GREEN}Running 'docker-compose $*' in $project${RESET}"
    case "$1" in
        "restart")
        (
            cd "$project" &&
            docker-compose down &&
            docker-compose pull &&
            docker-compose up -d
        )
        ;;
        "update")
        (
            cd "$project" &&
            docker-compose pull &&
            docker-compose up -d
        )
        ;;
        *)
        (cd "$project" && docker-compose "$@")
        ;;
    esac
done

