services:

  unifi:
    image: linuxserver/unifi-controller
    container_name: unifi
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      MEM_LIMIT: 2048
      MEM_STARTUP: 1024
    volumes:
      - ${DATADIR}/unifi/config:/config
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    restart: always
